### ISSUE TITLE
INPUT plugin

### ISSUE THREAD

**Issue by ivlevaleksandr4** [jeongukjae/flb-plugin-sample#1]
What if i want to implement custom INPUT plugin? So it's not enough to simplify flb_input.h etc. I have to build up whole Fluent Bit ecosystem don't I?

**Comment by jeongukjae** [comment]
Not sure, this is pretty outdated. If the fluent bit support this one (https://github.com/fluent/fluent-bit/issues/7028), you can easily leverage fluent bit interface. but sadly that issue is closed :cry:

**Comment by ivlevaleksandr4** [comment]
Yes, i've already created static plugin for Fluent Bit, using only C
But now i need create C++ plugin, i can't do it directly using Fluent Bit repository, bc it's fully C project(and API creation gonna be so long time)
So i decided to create DSO, for your FILTER plugin it's pretty simple. But for INPUT plugin i need fluent-bit events, collectors, chunks. How can i provide it?

**Comment by ivlevaleksandr4** [comment]
and yeah, this issue is still exist :)
![image](https://github.com/user-attachments/assets/d36fa7e6-7bec-4824-b014-3b4e49d46a5d)

**Comment by jeongukjae** [comment]
this repository code will be break with latest version of fluent bit.
so at the end, I just forked fluent bit and rewrite some plugins into C. (in my case, plugins are not that bit, so it was easy to rewrite)
I'm not sure how you should do in that case.

For importing issue, I just bypassed that by patching source codes and linking required header files into my codebase.

**Comment by ivlevaleksandr4** [comment]
okay, i see
what do you think if i develop PARSER/FILTER plugin for TAIL? 
My target is logging binary data, but TAIL can't read it directly. I already have code of engine, that will process this data. So what do u think on putting the logic of this engine inside of a FILTER/PARSER plugin? TAIL will be used just for tracking files. 
Engine is fully C++ project, so it needed to be DSO plugin. 

--

Thank you for communication!

**Comment by jeongukjae** [comment]
have you considered about wasm plugin?

https://docs.fluentbit.io/manual/development/wasm-input-plugins
https://docs.fluentbit.io/manual/development/wasm-filter-plugins

I think if you don't have any dependencies that is hard to compile to wasm, it should be better to use wasm not to modify something in fluent bit.

I don't know how big is your project, but if I were you, I would choose different way to implement it rather than develop Parser/Filter plugin in C++. (Maybe just use message queue and consume another server written in C++? or maybe implement gRPC streaming server?) Compiling C++ project and using it as fluent bit plugin is possible way, but I don't think it is good way.

**Comment by ivlevaleksandr4** [comment]
Yes, i read about WASM, but this is not what i am searching for. Let me be more specific. I use P7 logger https://baical.net/p7.html at my other project. It's async and working pretty fast. As a result i got 100+ binary logs in real time. I can process these logs via Baical Engine(same developing team as P7) https://baical.net/index.html
Of course i can track files in fluent bit, then start Baical Engine, then process logs and then send them into OpenSearch via sockets or something else, and then kill Baical.But i am searching for something fast. No unnecessary steps  and minimal delay. So i need make Baical Engine and fluent bit friends somehow :)

**Comment by jeongukjae** [comment]
hope you have breaking through that issue well. I'm not familiar with your situation.
implementing without fluent bit may make your issue simpler.

**Comment by ivlevaleksandr4** [comment]
Something works, but I can't implement it without fluent bit. I chose the path of developing a full-fledged API to run C++ code directly from the static fluent bit plugin

**Comment by ivlevaleksandr4** [comment]
i mean i can't avoid fluent bit, because it's my teamlead's request
